  version: '2'

  services:
    app:
      container_name: ${APP_NAME}
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - APP_IMAGE=${APP_IMAGE}
          - INSTALL_WP_CLI=${INSTALL_WP_CLI}
          - INSTALL_MOOSH=${INSTALL_MOOSH}
          - INSTALL_XDEBUG=${INSTALL_XDEBUG}
          - INSTALL_COMPOSER=${INSTALL_COMPOSER}
      ports:
        - "${APP_PORT}:80"
      restart: always
      volumes:
        - ./www:/var/www/html
        - ./phpcs.xml:/usr/local/etc/phpcs.xml
      extra_hosts:
        - "host.docker.internal:host-gateway"
